/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JOptionPane;

/**
 *
 * @author VP
 */
public class m extends javax.swing.JFrame {

    String nome,senha,email,cpf,vermail,fone;
     int tamnome,tamemail,tamsenha,tamcpf,validado,tamfone;
    
    public m() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setSize(1290, 735);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panes = new javax.swing.JOptionPane();
        SENHA = new javax.swing.JPasswordField();
        fones = new javax.swing.JTextField();
        nomes = new javax.swing.JTextField();
        emails = new javax.swing.JTextField();
        cpfs = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        fundos = new javax.swing.JLabel();

        panes.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                panesComponentHidden(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);
        getContentPane().add(SENHA);
        SENHA.setBounds(610, 330, 150, 30);
        getContentPane().add(fones);
        fones.setBounds(610, 450, 150, 30);
        getContentPane().add(nomes);
        nomes.setBounds(610, 290, 150, 30);
        getContentPane().add(emails);
        emails.setBounds(610, 370, 150, 30);
        getContentPane().add(cpfs);
        cpfs.setBounds(610, 410, 150, 30);

        jLabel2.setText("e-mail");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(540, 370, 40, 20);

        jLabel5.setText("cpf");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(550, 410, 40, 20);

        jLabel3.setText("fone");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(550, 450, 40, 20);

        jLabel4.setText("nome");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(540, 290, 40, 20);

        jLabel1.setText("senha");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(540, 330, 40, 20);

        jButton2.setText("cadastrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(540, 530, 90, 23);

        jLabel6.setText("                                      atenção o programa não aceita:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(480, 650, 380, 14);

        jLabel7.setText("-campos vazios");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(490, 670, 380, 14);

        jLabel8.setText("-cpf incorreto");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(490, 680, 240, 14);

        jButton1.setText("ja cadastrado");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(700, 530, 120, 23);

        fundos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/4dc7e634-3461-4376-bb31-3f96fca8c5c8.jpg"))); // NOI18N
        getContentPane().add(fundos);
        fundos.setBounds(0, -10, 1460, 710);

        setBounds(0, 0, 1298, 780);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int s=0;
        do{
         JOptionPane ss=new JOptionPane();
        nome=nomes.getText();
        tamnome=nome.length();
        if(nome.isEmpty() || tamnome<10 || tamnome>25){
                JOptionPane.showMessageDialog(null,"ERRO\n-VERIFIQUE SE NÃO HÁ UM CAMPO VAZIO\n-VERIFIQUE SE O TAMANHO NÃO ULTRAPASSA 10 OU 15 CARACTERES\n");
            s=1;
            break;
        }
        email=emails.getText();
        if(email.isEmpty()){
                JOptionPane.showMessageDialog(null,"ERRO\n-VERIFIQUE SE NÃO HÁ UM CAMPO VAZIO\n-VERIFIQUE SE O TAMANHO NÃO ULTRAPASSA 10 OU 15 CARACTERES\n");
            s=1;
            break;
        }
        if(email.endsWith("@gmail.com")){
            vermail=email;
            tamemail=vermail.length();
          
        }
        
        senha=SENHA.getText();
        tamsenha=senha.length();
        if(senha.isEmpty() || tamsenha<10 || tamsenha>20){
             JOptionPane.showMessageDialog(null,"ERRO\n-VERIFIQUE SE NÃO HÁ UM CAMPO VAZIO\n-VERIFIQUE SE O TAMANHO NÃO ULTRAPASSA 10 OU 15 CARACTERES\n");
            s=1;
            break;
        }

        
        cpf=cpfs.getText();    
        if(cpf.isEmpty()){
            JOptionPane.showMessageDialog(null,"CPF INVALIDADO");
            s=1;
            break;
          }
        tamcpf=cpf.length();
        cpf=cpf.replaceAll("\\.","");
        cpf=cpf.replaceAll("/","");
        cpf=cpf.replaceAll("-","");
        cpfr chamada=new cpfr();
        validado=chamada.CPF(cpf);
          if(validado!=1){
            JOptionPane.showMessageDialog(null,"CPF INVALIDADO");
            s=1;
            break;
          }

        fone=fones.getText();
        if(fone.isEmpty()){
            JOptionPane.showMessageDialog(null,"ERRO\n-VERIFIQUE SE O TELEFONE ESTA CORRETO\n");
            s=1;
            break;
        }
        tamfone=fone.length();
        if(tamfone!=11){
           JOptionPane.showMessageDialog(null,"ERRO\n-VERIFIQUE SE O TELEFONE ESTA CORRETO\n");
            s=1;
            break;
        }
        
      

        }while(cpf.isEmpty() || fone.isEmpty() || email.isEmpty() || nome.isEmpty() || tamnome<10 || tamnome>25|| tamemail<10 || tamemail>25 || tamsenha<10 || tamsenha>20 || validado!=1 || tamfone!=11);
        
        mm chama=new mm();
        String arquivo="dados.txt";
        if(s!=1){
        if(chama.printar(arquivo,nome, senha, vermail, cpf, fone)){
            System.out.printf("salvo com sucesso\n");
        }else{
            System.out.printf("deu errado\n");
        }
        }
   
       if(s!=1){
        bagui chame=new bagui();
        chame.setVisible(true);
        dispose();
       }
         
       
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void panesComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_panesComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_panesComponentHidden

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        bagui chinra=new bagui();
        chinra.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(m.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(m.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(m.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(m.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new m().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField SENHA;
    private javax.swing.JTextField cpfs;
    private javax.swing.JTextField emails;
    private javax.swing.JTextField fones;
    private javax.swing.JLabel fundos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField nomes;
    private javax.swing.JOptionPane panes;
    // End of variables declaration//GEN-END:variables
}