/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.io.File;
import javafx.embed.swing.JFXPanel;
import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author VP
 */
public class tela_2 extends javax.swing.JFrame {

    /**
     * Creates new form tela
     */
    public tela_2() {
        initComponents();
       this.setSize(1290, 750);
        this.setLocationRelativeTo(this);
   
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AJS = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        perfil = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jCheckBox5 = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel4 = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        AJS.setText("inicio");
        AJS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AJSActionPerformed(evt);
            }
        });
        getContentPane().add(AJS);
        AJS.setBounds(0, 0, 60, 23);

        jButton1.setText("configurações");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(220, 0, 120, 23);

        jButton2.setText("contatos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(60, 0, 90, 23);

        jButton3.setText("status");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(150, 0, 70, 23);

        jButton4.setText("arquivos");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(140, 420, 110, 20);

        jCheckBox1.setText("malwares");
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(290, 480, 130, 23);

        jLabel2.setText("enviar mensagem");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 530, 100, 20);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "problemas", "melhorias", "ajuda","denunciar","outros" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(120, 530, 140, 20);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 560, 530, 110);

        jCheckBox2.setText("visão");
        getContentPane().add(jCheckBox2);
        jCheckBox2.setBounds(150, 480, 110, 23);

        jCheckBox3.setText("notificação");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox3);
        jCheckBox3.setBounds(20, 480, 100, 23);

        jLabel6.setText("ativar");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 460, 40, 14);

        jLabel3.setText("trocar foto");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(410, 400, 130, 14);

        jLabel4.setText("ver pessoas bloqueadas");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(140, 460, 140, 14);

        jLabel5.setText("deixar ver se está online ou offline");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(780, 460, 190, 14);

        jLabel7.setText("editar toque");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 400, 110, 14);

        jButton5.setText("arquivos");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(20, 420, 110, 20);

        perfil.setText("                           sem perfil");
        getContentPane().add(perfil);
        perfil.setBounds(20, 150, 220, 230);

        jButton6.setText("arquivos");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(270, 420, 110, 20);

        jLabel9.setText("editar notificação");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(150, 400, 110, 14);

        jLabel10.setText("  tema");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(1110, 380, 50, 20);

        jButton8.setText("enviar");
        getContentPane().add(jButton8);
        jButton8.setBounds(550, 640, 90, 23);

        jButton9.setText("aplicar");
        getContentPane().add(jButton9);
        jButton9.setBounds(1080, 450, 90, 23);

        jCheckBox5.setText("ativar condição");
        getContentPane().add(jCheckBox5);
        jCheckBox5.setBounds(780, 480, 140, 23);

        jLabel11.setText("avisar sobre malwares");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(290, 460, 140, 14);

        jCheckBox6.setText("atualização");
        getContentPane().add(jCheckBox6);
        jCheckBox6.setBounds(430, 480, 130, 23);

        jCheckBox7.setText("status");
        getContentPane().add(jCheckBox7);
        jCheckBox7.setBounds(600, 480, 140, 23);

        jLabel13.setText("ativar seus conteudos de status");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(590, 460, 190, 14);

        jLabel12.setText("notificar sobre atualizações");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(430, 460, 160, 14);

        jRadioButton2.setText("claro");
        jPanel1.add(jRadioButton2);

        jRadioButton1.setText("escuro");
        jPanel1.add(jRadioButton1);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(1010, 410, 250, 30);

        jButton10.setText("trofeus");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(340, 0, 67, 23);

        jButton11.setText("aplicar");
        getContentPane().add(jButton11);
        jButton11.setBounds(1080, 540, 90, 23);

        jLabel14.setText("notificação de troféis");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(1070, 480, 140, 14);

        jRadioButton3.setText("ativar");
        jPanel2.add(jRadioButton3);

        jRadioButton4.setText("desativar");
        jPanel2.add(jRadioButton4);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(1010, 500, 240, 30);

        jLabel15.setText("nivel 1");
        jPanel3.add(jLabel15);
        jPanel3.add(jProgressBar1);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(1120, 0, 160, 50);

        jButton12.setText("Tocar");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton12);

        jButton13.setText("Parar");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton13);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(1010, 590, 240, 40);

        jLabel16.setText("Escutar som de toque");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(1070, 570, 140, 14);

        jLabel17.setText("escutar notificação");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(1070, 630, 120, 14);

        jButton17.setText("arquivos");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton17);
        jButton17.setBounds(390, 420, 110, 20);

        jLabel19.setText("editar foto de perfil");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(270, 400, 110, 14);

        jButton14.setText("Tocar");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton14);

        jButton15.setText("Parar");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton15);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(1010, 650, 240, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/3254aa65-0c96-4eaa-96b7-cf790d3eabfc.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -6, 1280, 720);
        ImageIcon icone=new ImageIcon("src/imagens/3254aa65-0c96-4eaa-96b7-cf790d3eabfc");
        icone.setImage(icone.getImage().getScaledInstance(perfil.getWidth(), perfil.getHeight(), 1));
        perfil.setIcon(icone);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       
     }//GEN-LAST:event_formWindowOpened
     
//fazer as validações dos campos//
    
  int x,m;
   public static void ma(int x) {
            final JFXPanel fxPanel = new JFXPanel();
      String uriString = new File("dark.mp3").toURI().toString();
      Media pick = new Media(uriString); 
      MediaPlayer player = new MediaPlayer(pick); 
      if(x==1){
        player.stop();
        player.play();
      }else{
      player.stop();
      }
      
           
    }  
   public static void ddaa(int m) {
      final JFXPanel fxPanel = new JFXPanel();
      String uriString = new File("cole.mp3").toURI().toString();
      Media pick = new Media(uriString); 
      MediaPlayer player = new MediaPlayer(pick); 
      if(m==1){
        player.stop();
        player.play();
      }else{
      player.stop();
      }
      
           
    }  
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

    private void AJSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AJSActionPerformed
        dispose(); 
        tela chame=new tela();
        chame.setVisible(true);    }//GEN-LAST:event_AJSActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose(); 
        tela_1 chame=new tela_1();
        chame.setVisible(true);    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose(); 
        tela_1_1 chame=new tela_1_1();
        chame.setVisible(true);    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose(); 
        tela_2 chame=new tela_2();
        chame.setVisible(true);    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       try{
            JFileChooser xx=new JFileChooser();
            int res=xx.showOpenDialog(null);
      if(res==JFileChooser.APPROVE_OPTION){
 
      }
      }catch(Exception e){
            e.printStackTrace();
      }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      try{
            JFileChooser xx=new JFileChooser();
            int res=xx.showOpenDialog(null);
      if(res==JFileChooser.APPROVE_OPTION){
 
      }
      }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton5ActionPerformed
    
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        ImageIcon icone=new ImageIcon("src/imagens/icone1.jpg");
        icone.setImage(icone.getImage().getScaledInstance(perfil.getWidth(), perfil.getHeight(), 1));
        perfil.setIcon(icone);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        dispose();
        trophy chum=new trophy();
        chum.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
       try{
            JFileChooser xx=new JFileChooser();
            int res=xx.showOpenDialog(null);
      if(res==JFileChooser.APPROVE_OPTION){
 
      }
      }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
      x=1;
      ma(x);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
      x=0;
      ma(x);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        m=1;
        ddaa(m);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        m=0;
        ddaa(m);
    }//GEN-LAST:event_jButton15ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AJS;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    public javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel perfil;
    // End of variables declaration//GEN-END:variables

  
}
