/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author VP
 */
public class tela_1 extends javax.swing.JFrame {
    String envi,novas;
    int r=0;
    /**
     * Creates new form tela
     */
    public tela_1() {
        initComponents();
         this.setSize(1295, 770);
        this.setLocationRelativeTo(this);
        ImageIcon icons=new ImageIcon("src/imagens/download.jpg");
        icons.setImage(icons.getImage().getScaledInstance(jLabel6.getWidth(), jLabel6.getHeight(), 1));
        jLabel6.setIcon(icons);
        ImageIcon icos=new ImageIcon("src/imagens/Bressan.jpg");
        icos.setImage(icos.getImage().getScaledInstance(jLabel4.getWidth(), jLabel4.getHeight(), 1));
        jLabel4.setIcon(icos);
        ImageIcon cons=new ImageIcon("src/imagens/4852c915-4bbf-41dc-9c48-3d047514a5eb.jpg");
        cons.setImage(cons.getImage().getScaledInstance(jLabel5.getWidth(), jLabel5.getHeight(), 1));
        jLabel5.setIcon(cons);
        ImageIcon ions=new ImageIcon("src/imagens/per.jpg");
        ions.setImage(ions.getImage().getScaledInstance(jLabel2.getWidth(), jLabel2.getHeight(), 1));
        jLabel2.setIcon(ions);
        ImageIcon iconsa=new ImageIcon("src/imagens/638c181c-1c9b-4140-b38e-6a345a6d847f.jpg");
        iconsa.setImage(iconsa.getImage().getScaledInstance(jLabel13.getWidth(), jLabel13.getHeight(), 1));
        jLabel13.setIcon(iconsa);
        
        
        ImageIcon FINAL=new ImageIcon("src/imagens/vv.jpg");
        FINAL.setImage(FINAL.getImage().getScaledInstance(jLabel12.getWidth(), jLabel12.getHeight(), 1));
        jLabel12.setIcon(FINAL);
        
         FINAL.setImage(FINAL.getImage().getScaledInstance(jLabel22.getWidth(), jLabel22.getHeight(), 1));
        jLabel22.setIcon(FINAL);
        
        
                
        ImageIcon blood=new ImageIcon("src/imagens/icone9.jpg");
        blood.setImage(blood.getImage().getScaledInstance(jLabel29.getWidth(), jLabel29.getHeight(), 1));
        jLabel29.setIcon(blood);
      
        ImageIcon borne=new ImageIcon("src/imagens/icone7.jpg");
        borne.setImage(borne.getImage().getScaledInstance(jLabel30.getWidth(), jLabel30.getHeight(), 1));
        jLabel30.setIcon(borne);
                 
        ImageIcon dark=new ImageIcon("src/imagens/icone5.jpg");
        dark.setImage(dark.getImage().getScaledInstance(jLabel25.getWidth(), jLabel25.getHeight(), 1));
        jLabel25.setIcon(dark);
                         
        ImageIcon souls=new ImageIcon("src/imagens/icone3.jpg");
        souls.setImage(souls.getImage().getScaledInstance(jLabel34.getWidth(), jLabel34.getHeight(), 1));
        jLabel34.setIcon(souls);
                         
        ImageIcon ast=new ImageIcon("src/imagens/icone15.jpg");
        ast.setImage(ast.getImage().getScaledInstance(jLabel32.getWidth(), jLabel32.getHeight(), 1));
        jLabel32.setIcon(ast);
                                
        ImageIcon muie=new ImageIcon("src/imagens/icone4.jpg");
        muie.setImage(muie.getImage().getScaledInstance(jLabel26.getWidth(), jLabel26.getHeight(), 1));
        jLabel26.setIcon(muie);
                                 
        ImageIcon caneta=new ImageIcon("src/imagens/ca.jpg");
        caneta.setImage(caneta.getImage().getScaledInstance(jLabel35.getWidth(), jLabel35.getHeight(), 1));
        jLabel35.setIcon(caneta);
        

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tsa1 = new javax.swing.JTextField();
        tsa = new javax.swing.JTextField();
        ars = new javax.swing.JTextField();
        var = new javax.swing.JTextField();
        copia = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jLabel36 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        AJS = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jComboBox7 = new javax.swing.JComboBox<>();
        jComboBox8 = new javax.swing.JComboBox<>();
        jComboBox9 = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        jButton11 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);
        getContentPane().add(tsa1);
        tsa1.setBounds(510, 480, 170, 30);
        getContentPane().add(tsa);
        tsa.setBounds(510, 570, 170, 30);
        getContentPane().add(ars);
        ars.setBounds(600, 620, 170, 30);
        getContentPane().add(var);
        var.setBounds(510, 670, 260, 40);
        getContentPane().add(copia);
        copia.setBounds(600, 520, 170, 30);

        jLabel37.setText("CONTATOS");
        getContentPane().add(jLabel37);
        jLabel37.setBounds(130, 300, 100, 14);
        getContentPane().add(jLabel22);
        jLabel22.setBounds(510, 270, 260, 450);

        jRadioButton1.setText("aceitar");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(1060, 310, 59, 23);

        jRadioButton2.setText("aceitar");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(1060, 370, 59, 23);

        jRadioButton3.setText("recusar");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(1160, 370, 90, 23);

        jRadioButton4.setText("aceitar");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton4);
        jRadioButton4.setBounds(1060, 430, 59, 23);

        jRadioButton5.setText("recusar");
        getContentPane().add(jRadioButton5);
        jRadioButton5.setBounds(1160, 430, 90, 23);

        jRadioButton6.setText("aceitar");
        getContentPane().add(jRadioButton6);
        jRadioButton6.setBounds(1060, 500, 59, 23);

        jRadioButton7.setText("recusar");
        getContentPane().add(jRadioButton7);
        jRadioButton7.setBounds(1160, 500, 90, 23);

        jRadioButton8.setText("recusar");
        getContentPane().add(jRadioButton8);
        jRadioButton8.setBounds(1160, 310, 90, 23);

        jRadioButton9.setText("aceitar");
        getContentPane().add(jRadioButton9);
        jRadioButton9.setBounds(1060, 560, 59, 23);

        jRadioButton10.setText("recusar");
        getContentPane().add(jRadioButton10);
        jRadioButton10.setBounds(1160, 560, 90, 23);

        jRadioButton11.setText("aceitar");
        jRadioButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton11);
        jRadioButton11.setBounds(1060, 610, 59, 23);

        jRadioButton12.setText("recusar");
        getContentPane().add(jRadioButton12);
        jRadioButton12.setBounds(1160, 610, 90, 23);

        jRadioButton13.setText("aceitar");
        getContentPane().add(jRadioButton13);
        jRadioButton13.setBounds(1060, 670, 59, 23);

        jRadioButton14.setText("recusar");
        getContentPane().add(jRadioButton14);
        jRadioButton14.setBounds(1160, 670, 90, 23);

        jLabel36.setText("cara da caneta");
        getContentPane().add(jLabel36);
        jLabel36.setBounds(1060, 650, 140, 14);

        jLabel23.setText("joão grandão");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(1060, 290, 160, 14);

        jLabel24.setText("gwyn");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(1060, 540, 120, 14);
        getContentPane().add(jLabel25);
        jLabel25.setBounds(1000, 400, 50, 50);
        getContentPane().add(jLabel26);
        jLabel26.setBounds(1000, 590, 50, 50);

        jLabel27.setText("jãozinho da bicicleta");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(1060, 350, 160, 14);

        jLabel28.setText("rasputhia");
        getContentPane().add(jLabel28);
        jLabel28.setBounds(1060, 590, 140, 14);
        getContentPane().add(jLabel29);
        jLabel29.setBounds(1000, 280, 50, 50);
        getContentPane().add(jLabel30);
        jLabel30.setBounds(1000, 340, 50, 50);

        jLabel31.setText("flavinho do pneu");
        getContentPane().add(jLabel31);
        jLabel31.setBounds(1060, 480, 160, 14);
        getContentPane().add(jLabel32);
        jLabel32.setBounds(1000, 530, 50, 50);

        jLabel33.setText("shaolin matador de porco");
        getContentPane().add(jLabel33);
        jLabel33.setBounds(1060, 410, 160, 14);
        getContentPane().add(jLabel34);
        jLabel34.setBounds(1000, 470, 50, 50);
        getContentPane().add(jLabel35);
        jLabel35.setBounds(1000, 650, 50, 50);

        AJS.setText("inicio");
        AJS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AJSActionPerformed(evt);
            }
        });
        getContentPane().add(AJS);
        AJS.setBounds(0, 0, 70, 23);

        jButton1.setText("configurações");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(220, 0, 110, 23);

        jButton2.setText("contatos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(70, 0, 90, 23);

        jButton3.setText("status");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(160, 0, 63, 23);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 570, 70, 70);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 490, 70, 70);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 650, 70, 70);

        jLabel7.setText("Bolsolula");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(90, 660, 140, 14);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 400, 70, 70);

        jLabel9.setText("Cynara");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(90, 510, 140, 14);

        jLabel8.setText("Bressan");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(90, 420, 140, 20);

        jButton4.setText("procurar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(250, 230, 80, 23);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(250, 190, 210, 30);

        jButton5.setText("enviar pedido");
        getContentPane().add(jButton5);
        jButton5.setBounds(343, 230, 110, 23);
        getContentPane().add(jLabel12);
        jLabel12.setBounds(990, 280, 290, 420);

        jLabel11.setText("nome/numero");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(160, 200, 90, 14);
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, 310, 70, 70);

        jLabel3.setText("Iolanda");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 340, 80, 14);

        jLabel14.setText("Perfeto");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(90, 590, 140, 14);
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 110, 160, 180);

        jButton9.setText("trofeus");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(330, 0, 67, 23);

        jLabel15.setText("nivel 1");
        jPanel3.add(jLabel15);
        jPanel3.add(jProgressBar1);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(1120, 0, 160, 50);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "grupo 1", "grupo 2", "grupo 3", "grupo 4" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(90, 460, 70, 20);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "grupo 1", "grupo 2", "grupo 3", "grupo 4" }));
        getContentPane().add(jComboBox6);
        jComboBox6.setBounds(90, 550, 70, 20);

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "grupo 1", "grupo 2", "grupo 3", "grupo 4" }));
        getContentPane().add(jComboBox7);
        jComboBox7.setBounds(90, 630, 70, 20);

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "grupo 1", "grupo 2", "grupo 3", "grupo 4" }));
        getContentPane().add(jComboBox8);
        jComboBox8.setBounds(90, 700, 70, 20);

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "grupo 1", "grupo 2", "grupo 3", "grupo 4" }));
        getContentPane().add(jComboBox9);
        jComboBox9.setBounds(90, 380, 70, 20);

        jLabel16.setText("Adicionar no grupo");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(90, 440, 140, 14);

        jLabel17.setText("Adicionar no grupo");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(90, 530, 140, 14);

        jLabel18.setText("Adicionar no grupo");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(90, 610, 140, 14);

        jLabel19.setText("Adicionar no grupo");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(90, 680, 140, 14);

        jLabel20.setText("Adicionar no grupo");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(90, 360, 140, 14);

        jLabel21.setText("pedidos de amizade");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(1090, 260, 120, 14);

        jButton8.setText("ENVIAR");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);

        jButton6.setText("AUDIO");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);

        jButton7.setText("ARQUIVO");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);

        jButton10.setText("CHAMADA");
        jPanel1.add(jButton10);

        jRadioButton15.setText("privado");
        jPanel1.add(jRadioButton15);

        jRadioButton16.setText("publico");
        jPanel1.add(jRadioButton16);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(780, 540, 120, 180);

        jButton11.setText("aplicar");
        getContentPane().add(jButton11);
        jButton11.setBounds(1120, 700, 63, 23);

        jCheckBox1.setText("bloquear");
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(180, 380, 100, 20);

        jCheckBox2.setText("bloquear");
        getContentPane().add(jCheckBox2);
        jCheckBox2.setBounds(180, 550, 100, 20);

        jCheckBox3.setText("bloquear");
        getContentPane().add(jCheckBox3);
        jCheckBox3.setBounds(180, 630, 100, 20);

        jCheckBox4.setText("bloquear");
        getContentPane().add(jCheckBox4);
        jCheckBox4.setBounds(180, 700, 100, 20);

        jCheckBox5.setText("bloquear");
        getContentPane().add(jCheckBox5);
        jCheckBox5.setBounds(180, 460, 100, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/3254aa65-0c96-4eaa-96b7-cf790d3eabfc.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -40, 1280, 810);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       
     }//GEN-LAST:event_formWindowOpened

    private void AJSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AJSActionPerformed
        dispose(); 
        tela chame=new tela();
        chame.setVisible(true);    }//GEN-LAST:event_AJSActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose(); 
        tela_1 chame=new tela_1();
        chame.setVisible(true);    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose(); 
        tela_1_1 chame=new tela_1_1();
        chame.setVisible(true);    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose(); 
        tela_2 chame=new tela_2();
        chame.setVisible(true);    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        ImageIcon icone=new ImageIcon("src/imagens/icone1.jpg");
        icone.setImage(icone.getImage().getScaledInstance(jLabel10.getWidth(), jLabel10.getHeight(), 1));
        jLabel10.setIcon(icone);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        dispose();
        trophy chum=new trophy();
        chum.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try{
            JFileChooser xx=new JFileChooser();
            int res=xx.showOpenDialog(null);
      if(res==JFileChooser.APPROVE_OPTION){
 
      }
      }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton11ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
                 envi=var.getText();
                 ars.setText(envi);
                 
        try {
            if(r==0){
            Thread.sleep(11);
            tsa.setText("eae beleza");
            novas=envi;
            r=1;
            }else if(r==1){
                copia.setText(novas);
                tsa1.setText("eae beleza");
                tsa.setText("to de boas");
            }
            
        } catch (InterruptedException ex) {
            Logger.getLogger(tela_1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AJS;
    private javax.swing.JTextField ars;
    private javax.swing.JTextField copia;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField tsa;
    private javax.swing.JTextField tsa1;
    private javax.swing.JTextField var;
    // End of variables declaration//GEN-END:variables
}
