/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author VP
 */
public class trophy extends javax.swing.JFrame {
 int r=0;
    /**
     * Creates new form trophy
     */
    public trophy() {
        initComponents();
            this.setSize(750, 760);
            
        ImageIcon icons=new ImageIcon("src/imagens/vv.jpg");
        icons.setImage(icons.getImage().getScaledInstance(jLabel13.getWidth(), jLabel13.getHeight(), 1));
        jLabel13.setIcon(icons);
        
         ImageIcon gomu=new ImageIcon("src/imagens/vv.jpg");
        gomu.setImage(gomu.getImage().getScaledInstance(jLabel44.getWidth(), jLabel44.getHeight(), 1));
        jLabel44.setIcon(gomu);
       
         ImageIcon ouro=new ImageIcon("src/imagens/ouro.jpg");
        ouro.setImage(ouro.getImage().getScaledInstance(jLabel19.getWidth(), jLabel19.getHeight(), 1));
        jLabel19.setIcon(ouro);
        
        ouro.setImage(ouro.getImage().getScaledInstance(jLabel45.getWidth(), jLabel45.getHeight(), 1));
        jLabel45.setIcon(ouro);
               
   
        ImageIcon prata=new ImageIcon("src/imagens/prata.jpg");
        prata.setImage(prata.getImage().getScaledInstance(jLabel22.getWidth(), jLabel22.getHeight(), 1));
        jLabel22.setIcon(prata);
        
        prata.setImage(prata.getImage().getScaledInstance(jLabel23.getWidth(), jLabel23.getHeight(), 1));
        jLabel23.setIcon(prata);
             
      
        ImageIcon bronze=new ImageIcon("src/imagens/bronze.jpg");
        bronze.setImage(bronze.getImage().getScaledInstance(jLabel21.getWidth(), jLabel21.getHeight(), 1));
        jLabel21.setIcon(bronze);
        
        bronze.setImage(bronze.getImage().getScaledInstance(jLabel20.getWidth(), jLabel20.getHeight(), 1));
        jLabel20.setIcon(bronze);
        
        ImageIcon kratos=new ImageIcon("src/imagens/1024px-NYCS-bull-trans-1.svg.png");
        kratos.setImage(kratos.getImage().getScaledInstance(var1.getWidth(), var1.getHeight(), 1));
        var1.setIcon(kratos);
                
        ImageIcon astraea=new ImageIcon("src/imagens/768px-NYCS-bull-trans-2.svg.png");
        astraea.setImage(astraea.getImage().getScaledInstance(var2.getWidth(), var2.getHeight(), 1));
        var2.setIcon(astraea);
                
        ImageIcon say_my_name=new ImageIcon("src/imagens/NYCS-bull-trans-3.svg.png");
        say_my_name.setImage(say_my_name.getImage().getScaledInstance(var3.getWidth(), var3.getHeight(), 1));
        var3.setIcon(say_my_name);
                               
        ImageIcon artorias=new ImageIcon("src/imagens/WIVB_Logo.png");
        artorias.setImage(artorias.getImage().getScaledInstance(var4.getWidth(), var4.getHeight(), 1));
        var4.setIcon(artorias);
      
        ImageIcon you=new ImageIcon("src/imagens/5_Kanal.png");
        you.setImage(you.getImage().getScaledInstance(var5.getWidth(), var5.getHeight(), 1));
        var5.setIcon(you);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AJS = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        var1 = new javax.swing.JLabel();
        var3 = new javax.swing.JLabel();
        var4 = new javax.swing.JLabel();
        var2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        var5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel43 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        AJS.setText("inicio");
        AJS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AJSActionPerformed(evt);
            }
        });
        getContentPane().add(AJS);
        AJS.setBounds(0, 0, 60, 23);

        jButton4.setText("ERRO NÃO APERTE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(0, 680, 170, 23);

        jLabel2.setText("complete os niveis abaixo  para liberar mais");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 260, 290, 14);
        getContentPane().add(jLabel45);
        jLabel45.setBounds(310, 560, 80, 50);
        getContentPane().add(var1);
        var1.setBounds(10, 290, 40, 40);
        getContentPane().add(var3);
        var3.setBounds(10, 430, 40, 40);
        getContentPane().add(var4);
        var4.setBounds(10, 490, 40, 40);
        getContentPane().add(var2);
        var2.setBounds(10, 360, 40, 40);

        jLabel7.setText("nivel 1");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 290, 60, 14);

        jLabel8.setText("nivel 2");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 360, 80, 14);

        jLabel9.setText("nivel 4");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(60, 490, 90, 14);

        jLabel10.setText("nivel 3");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(60, 430, 110, 14);

        jLabel11.setText("nivel 5");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(60, 550, 90, 14);
        getContentPane().add(var5);
        var5.setBounds(10, 550, 40, 40);

        jLabel14.setText("- gifs");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(60, 310, 110, 14);

        jLabel15.setText("- nova tela do uni chat");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(60, 380, 150, 14);

        jLabel16.setText("- novo toque exclusivo");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(60, 450, 150, 14);

        jLabel17.setText("- mensagem do desenvolvedor");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(60, 510, 180, 14);

        jLabel18.setText("- novo sistema exclusivo");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(60, 570, 150, 14);
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, 280, 250, 400);
        getContentPane().add(jLabel19);
        jLabel19.setBounds(310, 310, 80, 50);
        getContentPane().add(jLabel20);
        jLabel20.setBounds(310, 370, 80, 50);
        getContentPane().add(jLabel21);
        jLabel21.setBounds(310, 430, 80, 50);
        getContentPane().add(jLabel22);
        jLabel22.setBounds(310, 490, 80, 50);
        getContentPane().add(jLabel23);
        jLabel23.setBounds(310, 630, 80, 50);

        jLabel24.setText("TROFEUS DE HOJE");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(440, 260, 120, 14);

        jLabel25.setText("easter egg");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(390, 310, 120, 14);

        jLabel26.setText("minha primeira mensagem");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(390, 370, 180, 14);

        jLabel27.setText("hoje não");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(390, 430, 120, 14);

        jLabel28.setText("secret");
        getContentPane().add(jLabel28);
        jLabel28.setBounds(390, 490, 120, 14);

        jLabel29.setText("talvez um dia...");
        getContentPane().add(jLabel29);
        jLabel29.setBounds(390, 560, 120, 14);

        jLabel30.setText("hora da verdade");
        getContentPane().add(jLabel30);
        jLabel30.setBounds(390, 630, 120, 14);

        jLabel31.setText("descubra o easter egg");
        getContentPane().add(jLabel31);
        jLabel31.setBounds(390, 330, 150, 14);

        jLabel32.setText("mande uma mensagem");
        getContentPane().add(jLabel32);
        jLabel32.setBounds(390, 390, 170, 14);

        jLabel33.setText("desative as notificações");
        getContentPane().add(jLabel33);
        jLabel33.setBounds(390, 450, 140, 14);
        getContentPane().add(jLabel34);
        jLabel34.setBounds(390, 510, 90, 0);

        jLabel35.setText("ganhe um premio de melhor aep");
        getContentPane().add(jLabel35);
        jLabel35.setBounds(390, 580, 190, 14);

        jLabel36.setText("avalie o app uni chat");
        getContentPane().add(jLabel36);
        jLabel36.setBounds(390, 650, 140, 14);

        jLabel37.setText("50 pontos");
        getContentPane().add(jLabel37);
        jLabel37.setBounds(613, 650, 60, 14);

        jLabel38.setText("100 pontos");
        getContentPane().add(jLabel38);
        jLabel38.setBounds(610, 580, 70, 14);

        jLabel39.setText("50 pontos");
        getContentPane().add(jLabel39);
        jLabel39.setBounds(613, 510, 60, 14);

        jLabel40.setText("10 pontos");
        getContentPane().add(jLabel40);
        jLabel40.setBounds(610, 450, 60, 14);

        jLabel41.setText("10 pontos");
        getContentPane().add(jLabel41);
        jLabel41.setBounds(610, 390, 60, 14);

        jLabel42.setText("100 pontos");
        getContentPane().add(jLabel42);
        jLabel42.setBounds(610, 330, 70, 14);
        getContentPane().add(jProgressBar1);
        jProgressBar1.setBounds(570, 40, 146, 14);

        jLabel43.setText("nivel 1");
        getContentPane().add(jLabel43);
        jLabel43.setBounds(630, 20, 50, 14);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(560, 10, 160, 60);
        getContentPane().add(jLabel44);
        jLabel44.setBounds(300, 280, 400, 410);

        jButton2.setText("contatos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(60, 0, 90, 23);

        jButton3.setText("status");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(150, 0, 70, 23);

        jButton1.setText("configurações");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(220, 0, 120, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/3254aa65-0c96-4eaa-96b7-cf790d3eabfc.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-300, 0, 1040, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AJSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AJSActionPerformed
        dispose();
        tela chame=new tela();
        chame.setVisible(true);
    }//GEN-LAST:event_AJSActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
        tela_1 chame=new tela_1();
        chame.setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
        tela_1_1 chame=new tela_1_1();
        chame.setVisible(true);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        tela_2 chame=new tela_2();
        chame.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      
        
       r=r+1;
       if(r==10){
           JOptionPane.showMessageDialog(null,"pare com isso");
       }else if(r==20){
           JOptionPane.showMessageDialog(null,"você não sabe ler");
       }else if(r==30){
               JOptionPane.showMessageDialog(null,"meu deus da pra parar");
       }else if(r==40){
            JOptionPane.showMessageDialog(null,"sabe quanto tempo levei pra fazer isso");
       }else if(r==50){
            JOptionPane.showMessageDialog(null,"você não tem nada melhor pra fazer ?");
       }else if(r==60){
             JOptionPane.showMessageDialog(null,"chegou mensagem pra você");
       }else if(r==70){
              JOptionPane.showMessageDialog(null,"duvido você adivinhar qual desenvolvedor fez isso");
       }else if(r==80){
           JOptionPane.showMessageDialog(null,"você é persistente eu adimito");
       }else if(r==90){
             JOptionPane.showMessageDialog(null,"você não vai ganhar trofeu por isso");
       }else if(r==100){
                 JOptionPane.showMessageDialog(null,"por quanto tempo você vai fazer isso ?");
       }else if(r==110){
                  JOptionPane.showMessageDialog(null,"quer ouvir uma história ?");
       }else if(r==120){
            JOptionPane.showMessageDialog(null,"se continuar clicando o aplicativo vai executar um malware pra infectar seu conputador");
       }else if(r==130){
            JOptionPane.showMessageDialog(null,"noooooooooooooooooossa que pessoa chata");
       }else if(r==140){
            JOptionPane.showMessageDialog(null,"parabens você chegou até aqui e não ganhou nada,KKKKKKKKKKKKKKK\nESTOU RINDO DA SUA CARA");
       }else if(r==150){
           JOptionPane.showMessageDialog(null,"olha esse é meu ultimo aviso a partir daqui você está sozinho\nCONTINUE POR SUA CONTA E RISCO");
       }else if(r==160){
                  JOptionPane.showMessageDialog(null,"não gostei de the last of us 2");
       }else if(r==170){ 
            JOptionPane.showMessageDialog(null,"a pipa do vovo não sobe mais");
       }else if(r==180){ 
           JOptionPane.showMessageDialog(null,"all you have to do is follow the damn aplication user");
       }else if(r==190){ 
           JOptionPane.showMessageDialog(null,"ATENÇÃO SEU PC VAI REINICIAR EM");
       }else if(r==200){ 
           JOptionPane.showMessageDialog(null,"5");
       }else if(r==210){ 
           JOptionPane.showMessageDialog(null,"4");
       }else if(r==220){ 
           JOptionPane.showMessageDialog(null,"3");
       }else if(r==230){ 
           JOptionPane.showMessageDialog(null,"2-plot twists: eu não sou seu pai");
       }else if(r==240){ 
           JOptionPane.showMessageDialog(null,"etnerf arp sart ed aste megasnem asse-1");
       }else if(r==250){
           JOptionPane.showMessageDialog(null,"vou ir jantar adios");
       }else if(r==500){
            JOptionPane.showMessageDialog(null,"what are you buying,HEHEHEHE,a friend of mine said that");
        dispose();
        easter_egg chame=new easter_egg();
        chame.setVisible(true);
       }
   
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(trophy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(trophy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(trophy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(trophy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new trophy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AJS;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel var1;
    private javax.swing.JLabel var2;
    private javax.swing.JLabel var3;
    private javax.swing.JLabel var4;
    private javax.swing.JLabel var5;
    // End of variables declaration//GEN-END:variables
}
