var m,s,d,r;
        m=0;
        s=0;
        d=0;
        r=0;
        function CDS(){
            document.getElementById('nova').innerHTML="<h1>Canto do Sabor</h1>";
            if(m==0){
                document.getElementById('novo').innerHTML="<h2>pão rústico de bacon e ervas</h2><br><p>2 xícaras de chá ou 320 gramas de farinha de trigo<br>2 colheres de chá ou 5 gramas de fermento em pó<br>2 colheres de chá ou 5 gramas de sal<br>1 xícara de chá ou 150 gramas de bacon frito e picado<br>2 xícaras de chá ou 230 gramas de muçarela ralada no ralo grosso<br>Meia xícara de chá ou 100 gramas de manteiga gelada em cubos<br>Alecrim, salsa e tomilho picadinhos a gosto<br>1 pote ou 170 gramas de iogurte natural<br>1 ovo batido<br>Modo de Preparo<br>1. Coloque em uma tigela 2 xícaras de chá de farinha de trigo, 2 colheres de chá de fermento em pó , 2 colheres de chá de sal, 1 xícara de chá de bacon picado e frito, 2 xícaras de chá de muçarela ralada no ralo grosso e misture. Adicione meia xícara de chá de manteiga gelada em cubos, alecrim, salsa e tomilho picadinhos a gosto e misture bem, sem sovar muito, até obter uma farofa.<br>2. Acrescente 1 pote de iogurte natural e misture até formar uma massa.<br>3. Em uma assadeira (de 30 centímetros X 18 centímetros X 4 centímetros de altura) untada com manteiga coloque a massa espalhando bem, pincele 1 ovo batido na superfície e leve para assar em forno médio preaquecido a 160 graus por aproximadamente 30 minutos.<br>4. Retire do forno, desenforme e deixe sobre uma grade. Sirva em seguida.</p><br><br><br>";
                m=m+1;
            }else if(m==1){
                document.getElementById('novo').innerHTML="<h2>biscoitos</h2><br><p>200 gramas de farinha de trigo<br>135 gramas de açúcar<br>Meia colher de chá de fermento em pó<br>1 pitada de sal<br>100 gramas de manteiga derretida<br>1 ovo grande<br>200 gramas de chocolate meio amargo ou ao leite picado<br>Raspas de laranja ao gosto<br>Modo de Preparo<br>1. Em uma tigela, misture a farinha, o açúcar, o fermento e o sal. Se usar manteiga com sal desconsidere o sal da receita.<br>2. Coloque a manteiga derretida, o ovo e misture até obter uma massa compacta.<br>3. Acrescente as raspas de laranja e o chocolate picado.<br>4. Forme uma bola única e envolva com plástico filme. Leve para gelar por 30 minutos<br>5. Pré-aqueça o forno a 180 graus.<br>6. Forme bolinhas com a massa e leve ao forno por cerca de 14 minutos. Não deixe assar demais.<br>7. Retire os biscoitos e deixe resfriar sobre uma grade.<br>8. Conserve-os em pote hermeticamente fechado por cerca de 15 dias.</p>";
                m=m+1;
            }else{
                document.getElementById('novo').innerHTML="<h2>Cachorro-quente folhado</h2><p>1 pacote de mini salsichas<br>1 pacote de massa folhada laminada<br>1 gema de ovo<br>Modo de Preparo<br>1. Preaqueça o forno a 180 graus Celsius (temperatura ambiente).<br>2. Coloque as salsichas para cozinhar por 5 minutos.<br>3. Em uma tábua, corte a massa folhada em quadrados e, depois, os quadrados em diagonal, formando dois triângulos.<br>4. Corte as salsichas pela metade, no sentido do comprimento para ficarem mais finas.<br>5. Coloque em cada triângulo da massa folhada uma metade da salsicha. Enrole a salsicha na massa folhada.<br>6. Pincele o cachorro-quente com a gema do ovo para que eles fiquem dourados.<br>7. Leve o cachorro-quente folhado para assar por 20 minutos.</p><br>";
                m=0;
            }
        }

        function BS(){
            document.getElementById('nova').innerHTML="<h1>Belo Sabor</h1>";
            if(s==0){
                document.getElementById('novo').innerHTML="<h2>Espetinho de Salsicha</h2><br><p>10 salsichas cozidas<br>10 fatias de queijo muçarela (1 fatia para cada salsicha)<br>200 gramas de farinha de trigo<br>200 gramas de farinha de milho<br>200 mililitros de leite integral<br>2 ovos<br>2 colheres de sopa de fermento em pó<br>Queijo parmesão ralado a gosto<br>Sal a gosto<br>Óleo<br>10 palitos de churrasco<br>odo de Preparo - Espetinho de Salsicha<br>1. Bata todos os ingredientes no liquidificador.<br>2. Enrole a muçarela na salsicha, e espete no palito.<br>3. Mergulhe a salsicha no creme de farinhas e frite em óleo bem quente.<br>4. Sirva com molho ros(maionese e catchup) ou outro de sua preferência.</p>";
                s=s+1;
            }else if(s==1){
                document.getElementById('novo').innerHTML="<h2>Pão de queijo</h2><p>800 g de polvilho azedo<br>1 xícara de água<br>1 xícara de leite<br>1/2 xícara de óleo<br>2 ovos<br>100 g de queijo parmesão ralado<br>sal a gosto<br>MODO DE PREPARO<br>Em uma panela, ferva a água e acrescente o leite, o óleo e o sal.<br>Adicione o polvilho aos poucos até dar liga. Pode ser que você não precise usar os 800g, então coloque devagar e sove a massa até soltar da mão: esse é o ponto.<br>Quando a massa estiver morna, acrescente o queijo parmesão, os ovos e misture bem.<br>Junte as mãos e enrole bolinhas de 2 cm de diâmetro.<br>Disponha as bolinhas em uma assadeira untada com óleo, deixando um espaço entre elas.<br>Asse em forno médio (180º C), preaquecido, por cerca de 40 minutos.</p>";  
                s=s+1;
            }else{
                document.getElementById('novo').innerHTML="<h2>Picanha suína com abóbora assada</h2><br><p>1 picanha suína Sadia<br>Sal a gosto<br>Pimenta-do-reino a gosto<br>Ingredientes - Abóbora assada<br>1 abóbora-japonesa com casca fatiada<br>Sal a gosto<br>Pimenta-do-reino a gosto<br>2 colheres de sopa de azeite<br>Meia colher de chá de açúcar<br>Modo de Preparo - Picanha suína Sadia<br>1. Faça cortes perpendiculares na gordura da picanha suína Sadia, sem alcançar a carne.<br>2. Em uma frigideira em fogo baixo, frite a picanha com a gordura virada para baixo.<br>3. Quando a gordura estiver dourada, vire a picanha e deixe a carne dourar.<br>4. Acrescente 3 dentes de alho e um ramo de alecrim fresco e desligue o fogo.<br>5. Asse a picanha em forno preaquecido a 180 graus Celsius por 10 minutos.<br>6. Retire a picanha do forno e deixe a carne descansar por 5 minutos antes de fatiar.<br>Modo de Preparo - Abóbora assada<br>1. Coloque as fatias de abóbora em um tabuleiro e adicione sal, pimenta-do-reino, azeite e açúcar sobre elas.<br>2. Asse em forno preaquecido a 180 graus Celsius por 30 minutos.</p>";  
                s=0;
            }
        }

        function RZ(){
            document.getElementById('nova').innerHTML="<h1>Restaurante do zé</h1>";
          if(d==0){
              document.getElementById('novo').innerHTML="<h2>Macarrão alho e óleo</h2><br><p>200 g de massa<br>2 l de água ou caldo de legumes<br>1 colher de sobremesa rasa de sal<br>1/2 xícara de óleo de girassol ou canola, ou azeite<br>6 dentes de alho bem picados<br>1/2 xícara de cebolinha ou salsinha picadas<br>Modo de preparo<br>Leve a água para ferver, quando começar a ferver coloque o sal e a massa.<br>Verifique na embalagem o tempo de cozimento para al dente da massa escolhida, pois cada massa tem um tempo de cozimento. E sempre use 1 l de água para cada 100 g de massa, isto fará com que ela cozinhe por igual e não grude.<br>Aqueça o óleo em uma frigideira grande. Frite o alho em fogo bem baixo até que comece a dourar.<br>Junte a massa já cozida e escorrida, misture bem. Coloque a cebolinha e esta pronto.</p><br><br><br>"; 
              d=d+1;
          }else if(d==1){
             document.getElementById('novo').innerHTML="<h2>Carne louca</h2><p>8 1kg de maminha em cubos pequenos</p><p>4 tomates maduros em cubinhos (sem pele e sem semente)<br>1 pacote de Knorr Meu Assado Sabor Alho e Cebola<br>6 pães franceses (para montar o sanduíche)<br>MODO_PREPARO<br>1) Retire o saquinho plástico da embalagem de Knorr Meu Assado, abra-o com cuidado e separe o lacre. Apoie o saquinho sobre uma assadeira e coloque a maminha e o tomate.<br>2) Adicione o tempero Knorr Meu Assado sabor Alho e Cebola dentro do saquinho e misture bem.<br>3) Feche o saquinho com o lacre e leve ao forno a 180°C por 50 minutos.<br>4) Retire do forno, corte o saquinho, tendo cuidado com o vapor e transfira para uma travessa.<br>5) Sirva com pão francês para cada um montar o seu sanduíche.</p><br><br><br>";
              d=d+1;
          }else{
              document.getElementById('novo').innerHTML="<h2>Frango Xadrez</h2><br><p>500g de Peito Frango<br>½ Pimentão Vermelho<br>½ Pimentão Verde<br>½ Pimentão Amarelo<br>3 Colheres (sopa) de Molho Shoyu<br>3 Colheres (sopa) de Óleo de Gergelim<br>1 Colher (sopa) de Maisena<br>½ Xícara (chá) de Água<br>25g de Amendoim<br>Cebolinha (a gosto)<br>Instruções<br>Pique o frango em cubinhos e tempere com sal, pimenta do reino e suco de 1 limão.<br>Frite o frango até dourar com um fio de azeite e 1 colher (sopa) de Óleo de Gergelim<br>Junte os pimentões e misture bem.<br>Adicione o molho Shoyu o restante do óleo de gergelim e 1 colher (sopa) de Maisena diluida em ½ xícara (chá) de Água.<br>Misture até engrossar, finalize com amendoim torrado s/ sal, cebolinha e um pouco de gergelim</p><br>";
              d=0;
          }                                                  
        }

        function RTD(){
            document.getElementById('nova').innerHTML="<h1>Restaurante da tia dé</h1>";
          if(r==0){
              document.getElementById('novo').innerHTML="<h2>Purê de Batata</h2><br><p>3 batatas grandes<br>1 dente de alho grande<br>1 fio de azeite<br>Sal a gosto<br>1/2 colher de chá de curry (opcional)<br>Modo de preparo<br>Descasque as batatas e corte em pedaços.<br>Pique o alho bem finamente e coloque na panela com um fio de azeite e o curry se você desejar usar, deixe dourar levemente.<br>Assim que o alho começar a dourar coloque as batatas, misture bem e adicione pouca água, a água não deve cobrir as batatas!<br>Adicione o sal, tampe a panela e espere aproximadamente 10 minutos cozinhando em fogo baixo, cuidando apenas para que a água não seque completamente.<br>Com a ajuda de um garfo vá amassando os pedaços de batata tão logo eles já estejam macios, adicione mais água se achar necessário.<p><br><br><br>";
              r=r+1;
          }else if(r==1){
              document.getElementById('novo').innerHTML="<h2>Estrogonofe de frango</h2><br><p>500g Peito de Frango (em cubos)<br>½ Xícara (chá) de Creme de Leite<br>½ Xícara (chá) de Leite<br>1 Colher (sopa) de Maisena<br>1 Xícara (chá) de Champignon<br>10 Colheres (sopa) de Catchup<br>1 Colher (sopa) de Mostarda</br>Sal e Pimenta do Reino (a gosto)<br>1 Dente de Alho (opcional)<br>Instruções<br>Aqueça a panela, adicione cerca de 1 colher (sopa) de azeite / óleo e frite, junte os cubos de frango, tempere com sal e pimenta do reino e deixe fritar até que fiquem levemente dourados.<br>Adicione o champignon, 1 dente de alho picado (opcional), misture bem, junte o catchup, mostarda e misture bem para envolver todo o frango.<br>Dilua a maisena no leite (frio) e adicione na panela misturando bem em fogo baixo até que fique o molho fique bem cremoso.<br>Adicione o creme de leite e misture bem (tome cuidado para não ferver), assim que estiver tudo bem misturado desligue o fogo e sirva.</p><br><br><br>";
              r=r+1;
          }else{
              document.getElementById('novo').innerHTML="<h2>Peixe Ensopado</h2><br><p>1 kg do seu peixe preferido temperado om pelo menos 2 horas antes com limão, sal e pimenta-do-reino;<br>1 cebola em rodelas;<br>1 pimentão amarelo em rodelas;<br>1/2 pimentão verde em rodelas;<br>1 tomate fatiado;<br>1 vidro de leite de coco;<br>1 colher (sopa) cheia de extrato de tomate;<br>Sal e salsinha a gosto.<br>Cubra o fundo da panela com azeite espalhe as rodelas de cebola, em seguida os pimentões, os tomates, salpique um pouquinho de sal e coloque as postas de peixe. Eu gosto ainda de jogar por cima o resto do tempero que ficou no recipiente em que estava o peixe.Tampe a panela e deixe em fogo baixo por 20 minutos. Quando vc abrir a panela, o peixe e os vegetais terão soltado bastante líquido, aí é o momento de misturar o leite de coco com o extrato de tomate e adicionar por cima de tudo. Mantenha em fogo baixo e tampada por mais 5 minutos. Após este tempo é só acertar o sal e acrescentar salsinha.</p><br>";
              r=0;
          }                                          
        }